spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_mangement?createDatabaseIfNotExist=true
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true